# ============================================================
# Emart Kubernetes Namespace
# ============================================================
---
apiVersion: v1
kind: Namespace
metadata:
  name: emart-dev
  labels:
    environment: dev
    app: emart
---
apiVersion: v1
kind: Namespace
metadata:
  name: emart-staging
  labels:
    environment: staging
    app: emart
---
apiVersion: v1
kind: Namespace
metadata:
  name: emart-prod
  labels:
    environment: prod
    app: emart
